export const ActionTypes = {
  UPDATE_ROUND: "UPDATE_ROUND",
  UPDATE_ROUND_LENGTH: "UPDATE_ROUND_LENGTH",
  UPDATE_REST_LENGTH: "UPDATE_REST_LENGTH",
  UPDATE_END_OF_ROUND_COUNT: "UPDATE_END_OF_ROUND_COUNT",
  UPDATE_START_ROUND_COUNT: "UPDATE_START_ROUND_COUNT",
};
